### ISSUE TITLE
bigint: Failed to load bindings, pure JS will be used (try npm run rebuild?)

### ISSUE THREAD

**Issue by alex-r89** [mharj/minecraft-ping#5]
Hi,

Since installing this package, I see the following error in the console:

```bigint: Failed to load bindings, pure JS will be used (try npm run rebuild?)```

Unsure why this is or what I can do about it. Let me know if you need more info.

Node version `15.9.0`

**Comment by mharj** [comment]
No need to do anything, this is just warning that it uses JS for 64bit integers.
This will disappear when I'll change code to use actual NodeJS 64bit integers.
