### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by nashwik** [mharj/minecraft-ping#6]
ip: "weanarchyu.mcserv.fun"
my code:
```js
    const data = await ping(ip)
    console.log(data)
```
![image](https://user-images.githubusercontent.com/67203548/128779702-67e2342f-b0b8-419a-be92-76b1021448c0.png)

**Comment by mharj** [comment]
This server is sending broken handshake, as actual tcp package says that handshake information starts from offset 4 which is not ok as looks like information starts from offset 3 and fails on JSON decode because of this.
header:
```json
{ id: 0, length: 111, offset: 4 }
```
I expected that this will get fixed on MC server hopefully.

**Comment by mharj** [comment]
There is something strange on original implementation of packet size and offsets

**Comment by mharj** [comment]
quickly tested and now 0.0.7 fixes this issue
